### ISSUE TITLE
Add Opfor and Independent sides.

### ISSUE THREAD

**Issue by Freddo3000** [ARCOMM/ARCMT#106]
In order to keep dependencies to a minimum, only the following addons should be loaded:
```
ace
acex
acre2
cba_a3
cup_units
cup_vehicles
cup_vehicles_ace_compat
cup_weapons
cup_weapons_ace_compat
arc_misc
tmf
```

**Comment by BorderKeeper** [comment]
- Added INDFOR and OPFOR
- Filled out all attributes
- Slimmed down the ORBAT
- Renamed to ARCMT.vr
- WSL is now on his own net with other weapon groups
- Weapon groups have their own 343's now
- Renamed P to PHT, R to RVN and F to FLC as per convention
- Fixed missing name on Mortar leader
